# SPDX-FileCopyrightText: 2025 HongKongukah.com
# SPDX-License-Identifier: MIT

services:
  test-hongkongukah:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "8004:8000"
    env_file:
      - ../.env
