# SPDX-FileCopyrightText: 2025 HongKongukah.com
# SPDX-License-Identifier: MIT

name: Publish site

on:
  push:
    branches: ['main']

jobs:
  publish-website:
    runs-on: ubuntu-latest
    steps:
    - name: Update and deploy on server
      uses: appleboy/ssh-action@v1.0.1
      with:
        host: tekktrik.dev
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          # Change to directory
          cd /srv/www/hongkongukah-com

          # Update the repository
          git fetch
          git checkout main
          git config pull.rebase true
          git pull --rebase -ff

          # Start docker container
          make stop-prod
          make start-prod
